name: Compile ESPHome

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache PlatformIO & ESPHome
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cache/pip
            firmware/.esphome
          key: ${{ runner.os }}-esphome-${{ hashFiles('firmware/*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-esphome-

      - name: Install ESPHome
        run: |
          pip install esphome

      - name: Compile Firmware
        run: |
          esphome compile firmware/esp32-s3-smart-speaker.yaml

      - name: Upload Firmware and Source Code
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: esp-project-files
          path: |
            firmware/.esphome/build/*/.pioenvs/*/*.bin
            firmware/.esphome/build/*/src/main.cpp
